// Code generated by ent, DO NOT EDIT.

package searchdocument

import (
	"balanciz/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldCompanyID, v))
}

// EntityType applies equality check predicate on the "entity_type" field. It's identical to EntityTypeEQ.
func EntityType(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldEntityType, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldEntityID, v))
}

// DocNumber applies equality check predicate on the "doc_number" field. It's identical to DocNumberEQ.
func DocNumber(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldDocNumber, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitle, v))
}

// Subtitle applies equality check predicate on the "subtitle" field. It's identical to SubtitleEQ.
func Subtitle(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldSubtitle, v))
}

// TitleNative applies equality check predicate on the "title_native" field. It's identical to TitleNativeEQ.
func TitleNative(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitleNative, v))
}

// TitleLatin applies equality check predicate on the "title_latin" field. It's identical to TitleLatinEQ.
func TitleLatin(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitleLatin, v))
}

// TitleInitials applies equality check predicate on the "title_initials" field. It's identical to TitleInitialsEQ.
func TitleInitials(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitleInitials, v))
}

// MemoNative applies equality check predicate on the "memo_native" field. It's identical to MemoNativeEQ.
func MemoNative(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldMemoNative, v))
}

// DocDate applies equality check predicate on the "doc_date" field. It's identical to DocDateEQ.
func DocDate(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldDocDate, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldCurrency, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldStatus, v))
}

// URLPath applies equality check predicate on the "url_path" field. It's identical to URLPathEQ.
func URLPath(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldURLPath, v))
}

// ProjectorVersion applies equality check predicate on the "projector_version" field. It's identical to ProjectorVersionEQ.
func ProjectorVersion(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldProjectorVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldCompanyID, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityTypeGT applies the GT predicate on the "entity_type" field.
func EntityTypeGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldEntityType, v))
}

// EntityTypeGTE applies the GTE predicate on the "entity_type" field.
func EntityTypeGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldEntityType, v))
}

// EntityTypeLT applies the LT predicate on the "entity_type" field.
func EntityTypeLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldEntityType, v))
}

// EntityTypeLTE applies the LTE predicate on the "entity_type" field.
func EntityTypeLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldEntityType, v))
}

// EntityTypeContains applies the Contains predicate on the "entity_type" field.
func EntityTypeContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldEntityType, v))
}

// EntityTypeHasPrefix applies the HasPrefix predicate on the "entity_type" field.
func EntityTypeHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldEntityType, v))
}

// EntityTypeHasSuffix applies the HasSuffix predicate on the "entity_type" field.
func EntityTypeHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldEntityType, v))
}

// EntityTypeEqualFold applies the EqualFold predicate on the "entity_type" field.
func EntityTypeEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldEntityType, v))
}

// EntityTypeContainsFold applies the ContainsFold predicate on the "entity_type" field.
func EntityTypeContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldEntityType, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v uint) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldEntityID, v))
}

// DocNumberEQ applies the EQ predicate on the "doc_number" field.
func DocNumberEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldDocNumber, v))
}

// DocNumberNEQ applies the NEQ predicate on the "doc_number" field.
func DocNumberNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldDocNumber, v))
}

// DocNumberIn applies the In predicate on the "doc_number" field.
func DocNumberIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldDocNumber, vs...))
}

// DocNumberNotIn applies the NotIn predicate on the "doc_number" field.
func DocNumberNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldDocNumber, vs...))
}

// DocNumberGT applies the GT predicate on the "doc_number" field.
func DocNumberGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldDocNumber, v))
}

// DocNumberGTE applies the GTE predicate on the "doc_number" field.
func DocNumberGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldDocNumber, v))
}

// DocNumberLT applies the LT predicate on the "doc_number" field.
func DocNumberLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldDocNumber, v))
}

// DocNumberLTE applies the LTE predicate on the "doc_number" field.
func DocNumberLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldDocNumber, v))
}

// DocNumberContains applies the Contains predicate on the "doc_number" field.
func DocNumberContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldDocNumber, v))
}

// DocNumberHasPrefix applies the HasPrefix predicate on the "doc_number" field.
func DocNumberHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldDocNumber, v))
}

// DocNumberHasSuffix applies the HasSuffix predicate on the "doc_number" field.
func DocNumberHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldDocNumber, v))
}

// DocNumberIsNil applies the IsNil predicate on the "doc_number" field.
func DocNumberIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldDocNumber))
}

// DocNumberNotNil applies the NotNil predicate on the "doc_number" field.
func DocNumberNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldDocNumber))
}

// DocNumberEqualFold applies the EqualFold predicate on the "doc_number" field.
func DocNumberEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldDocNumber, v))
}

// DocNumberContainsFold applies the ContainsFold predicate on the "doc_number" field.
func DocNumberContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldDocNumber, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldTitle, v))
}

// SubtitleEQ applies the EQ predicate on the "subtitle" field.
func SubtitleEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldSubtitle, v))
}

// SubtitleNEQ applies the NEQ predicate on the "subtitle" field.
func SubtitleNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldSubtitle, v))
}

// SubtitleIn applies the In predicate on the "subtitle" field.
func SubtitleIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldSubtitle, vs...))
}

// SubtitleNotIn applies the NotIn predicate on the "subtitle" field.
func SubtitleNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldSubtitle, vs...))
}

// SubtitleGT applies the GT predicate on the "subtitle" field.
func SubtitleGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldSubtitle, v))
}

// SubtitleGTE applies the GTE predicate on the "subtitle" field.
func SubtitleGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldSubtitle, v))
}

// SubtitleLT applies the LT predicate on the "subtitle" field.
func SubtitleLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldSubtitle, v))
}

// SubtitleLTE applies the LTE predicate on the "subtitle" field.
func SubtitleLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldSubtitle, v))
}

// SubtitleContains applies the Contains predicate on the "subtitle" field.
func SubtitleContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldSubtitle, v))
}

// SubtitleHasPrefix applies the HasPrefix predicate on the "subtitle" field.
func SubtitleHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldSubtitle, v))
}

// SubtitleHasSuffix applies the HasSuffix predicate on the "subtitle" field.
func SubtitleHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldSubtitle, v))
}

// SubtitleIsNil applies the IsNil predicate on the "subtitle" field.
func SubtitleIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldSubtitle))
}

// SubtitleNotNil applies the NotNil predicate on the "subtitle" field.
func SubtitleNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldSubtitle))
}

// SubtitleEqualFold applies the EqualFold predicate on the "subtitle" field.
func SubtitleEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldSubtitle, v))
}

// SubtitleContainsFold applies the ContainsFold predicate on the "subtitle" field.
func SubtitleContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldSubtitle, v))
}

// TitleNativeEQ applies the EQ predicate on the "title_native" field.
func TitleNativeEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitleNative, v))
}

// TitleNativeNEQ applies the NEQ predicate on the "title_native" field.
func TitleNativeNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldTitleNative, v))
}

// TitleNativeIn applies the In predicate on the "title_native" field.
func TitleNativeIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldTitleNative, vs...))
}

// TitleNativeNotIn applies the NotIn predicate on the "title_native" field.
func TitleNativeNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldTitleNative, vs...))
}

// TitleNativeGT applies the GT predicate on the "title_native" field.
func TitleNativeGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldTitleNative, v))
}

// TitleNativeGTE applies the GTE predicate on the "title_native" field.
func TitleNativeGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldTitleNative, v))
}

// TitleNativeLT applies the LT predicate on the "title_native" field.
func TitleNativeLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldTitleNative, v))
}

// TitleNativeLTE applies the LTE predicate on the "title_native" field.
func TitleNativeLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldTitleNative, v))
}

// TitleNativeContains applies the Contains predicate on the "title_native" field.
func TitleNativeContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldTitleNative, v))
}

// TitleNativeHasPrefix applies the HasPrefix predicate on the "title_native" field.
func TitleNativeHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldTitleNative, v))
}

// TitleNativeHasSuffix applies the HasSuffix predicate on the "title_native" field.
func TitleNativeHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldTitleNative, v))
}

// TitleNativeEqualFold applies the EqualFold predicate on the "title_native" field.
func TitleNativeEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldTitleNative, v))
}

// TitleNativeContainsFold applies the ContainsFold predicate on the "title_native" field.
func TitleNativeContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldTitleNative, v))
}

// TitleLatinEQ applies the EQ predicate on the "title_latin" field.
func TitleLatinEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitleLatin, v))
}

// TitleLatinNEQ applies the NEQ predicate on the "title_latin" field.
func TitleLatinNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldTitleLatin, v))
}

// TitleLatinIn applies the In predicate on the "title_latin" field.
func TitleLatinIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldTitleLatin, vs...))
}

// TitleLatinNotIn applies the NotIn predicate on the "title_latin" field.
func TitleLatinNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldTitleLatin, vs...))
}

// TitleLatinGT applies the GT predicate on the "title_latin" field.
func TitleLatinGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldTitleLatin, v))
}

// TitleLatinGTE applies the GTE predicate on the "title_latin" field.
func TitleLatinGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldTitleLatin, v))
}

// TitleLatinLT applies the LT predicate on the "title_latin" field.
func TitleLatinLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldTitleLatin, v))
}

// TitleLatinLTE applies the LTE predicate on the "title_latin" field.
func TitleLatinLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldTitleLatin, v))
}

// TitleLatinContains applies the Contains predicate on the "title_latin" field.
func TitleLatinContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldTitleLatin, v))
}

// TitleLatinHasPrefix applies the HasPrefix predicate on the "title_latin" field.
func TitleLatinHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldTitleLatin, v))
}

// TitleLatinHasSuffix applies the HasSuffix predicate on the "title_latin" field.
func TitleLatinHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldTitleLatin, v))
}

// TitleLatinIsNil applies the IsNil predicate on the "title_latin" field.
func TitleLatinIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldTitleLatin))
}

// TitleLatinNotNil applies the NotNil predicate on the "title_latin" field.
func TitleLatinNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldTitleLatin))
}

// TitleLatinEqualFold applies the EqualFold predicate on the "title_latin" field.
func TitleLatinEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldTitleLatin, v))
}

// TitleLatinContainsFold applies the ContainsFold predicate on the "title_latin" field.
func TitleLatinContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldTitleLatin, v))
}

// TitleInitialsEQ applies the EQ predicate on the "title_initials" field.
func TitleInitialsEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldTitleInitials, v))
}

// TitleInitialsNEQ applies the NEQ predicate on the "title_initials" field.
func TitleInitialsNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldTitleInitials, v))
}

// TitleInitialsIn applies the In predicate on the "title_initials" field.
func TitleInitialsIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldTitleInitials, vs...))
}

// TitleInitialsNotIn applies the NotIn predicate on the "title_initials" field.
func TitleInitialsNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldTitleInitials, vs...))
}

// TitleInitialsGT applies the GT predicate on the "title_initials" field.
func TitleInitialsGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldTitleInitials, v))
}

// TitleInitialsGTE applies the GTE predicate on the "title_initials" field.
func TitleInitialsGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldTitleInitials, v))
}

// TitleInitialsLT applies the LT predicate on the "title_initials" field.
func TitleInitialsLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldTitleInitials, v))
}

// TitleInitialsLTE applies the LTE predicate on the "title_initials" field.
func TitleInitialsLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldTitleInitials, v))
}

// TitleInitialsContains applies the Contains predicate on the "title_initials" field.
func TitleInitialsContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldTitleInitials, v))
}

// TitleInitialsHasPrefix applies the HasPrefix predicate on the "title_initials" field.
func TitleInitialsHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldTitleInitials, v))
}

// TitleInitialsHasSuffix applies the HasSuffix predicate on the "title_initials" field.
func TitleInitialsHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldTitleInitials, v))
}

// TitleInitialsIsNil applies the IsNil predicate on the "title_initials" field.
func TitleInitialsIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldTitleInitials))
}

// TitleInitialsNotNil applies the NotNil predicate on the "title_initials" field.
func TitleInitialsNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldTitleInitials))
}

// TitleInitialsEqualFold applies the EqualFold predicate on the "title_initials" field.
func TitleInitialsEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldTitleInitials, v))
}

// TitleInitialsContainsFold applies the ContainsFold predicate on the "title_initials" field.
func TitleInitialsContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldTitleInitials, v))
}

// MemoNativeEQ applies the EQ predicate on the "memo_native" field.
func MemoNativeEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldMemoNative, v))
}

// MemoNativeNEQ applies the NEQ predicate on the "memo_native" field.
func MemoNativeNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldMemoNative, v))
}

// MemoNativeIn applies the In predicate on the "memo_native" field.
func MemoNativeIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldMemoNative, vs...))
}

// MemoNativeNotIn applies the NotIn predicate on the "memo_native" field.
func MemoNativeNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldMemoNative, vs...))
}

// MemoNativeGT applies the GT predicate on the "memo_native" field.
func MemoNativeGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldMemoNative, v))
}

// MemoNativeGTE applies the GTE predicate on the "memo_native" field.
func MemoNativeGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldMemoNative, v))
}

// MemoNativeLT applies the LT predicate on the "memo_native" field.
func MemoNativeLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldMemoNative, v))
}

// MemoNativeLTE applies the LTE predicate on the "memo_native" field.
func MemoNativeLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldMemoNative, v))
}

// MemoNativeContains applies the Contains predicate on the "memo_native" field.
func MemoNativeContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldMemoNative, v))
}

// MemoNativeHasPrefix applies the HasPrefix predicate on the "memo_native" field.
func MemoNativeHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldMemoNative, v))
}

// MemoNativeHasSuffix applies the HasSuffix predicate on the "memo_native" field.
func MemoNativeHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldMemoNative, v))
}

// MemoNativeIsNil applies the IsNil predicate on the "memo_native" field.
func MemoNativeIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldMemoNative))
}

// MemoNativeNotNil applies the NotNil predicate on the "memo_native" field.
func MemoNativeNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldMemoNative))
}

// MemoNativeEqualFold applies the EqualFold predicate on the "memo_native" field.
func MemoNativeEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldMemoNative, v))
}

// MemoNativeContainsFold applies the ContainsFold predicate on the "memo_native" field.
func MemoNativeContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldMemoNative, v))
}

// DocDateEQ applies the EQ predicate on the "doc_date" field.
func DocDateEQ(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldDocDate, v))
}

// DocDateNEQ applies the NEQ predicate on the "doc_date" field.
func DocDateNEQ(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldDocDate, v))
}

// DocDateIn applies the In predicate on the "doc_date" field.
func DocDateIn(vs ...time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldDocDate, vs...))
}

// DocDateNotIn applies the NotIn predicate on the "doc_date" field.
func DocDateNotIn(vs ...time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldDocDate, vs...))
}

// DocDateGT applies the GT predicate on the "doc_date" field.
func DocDateGT(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldDocDate, v))
}

// DocDateGTE applies the GTE predicate on the "doc_date" field.
func DocDateGTE(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldDocDate, v))
}

// DocDateLT applies the LT predicate on the "doc_date" field.
func DocDateLT(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldDocDate, v))
}

// DocDateLTE applies the LTE predicate on the "doc_date" field.
func DocDateLTE(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldDocDate, v))
}

// DocDateIsNil applies the IsNil predicate on the "doc_date" field.
func DocDateIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldDocDate))
}

// DocDateNotNil applies the NotNil predicate on the "doc_date" field.
func DocDateNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldDocDate))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldAmount))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldStatus, v))
}

// URLPathEQ applies the EQ predicate on the "url_path" field.
func URLPathEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldURLPath, v))
}

// URLPathNEQ applies the NEQ predicate on the "url_path" field.
func URLPathNEQ(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldURLPath, v))
}

// URLPathIn applies the In predicate on the "url_path" field.
func URLPathIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldURLPath, vs...))
}

// URLPathNotIn applies the NotIn predicate on the "url_path" field.
func URLPathNotIn(vs ...string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldURLPath, vs...))
}

// URLPathGT applies the GT predicate on the "url_path" field.
func URLPathGT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldURLPath, v))
}

// URLPathGTE applies the GTE predicate on the "url_path" field.
func URLPathGTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldURLPath, v))
}

// URLPathLT applies the LT predicate on the "url_path" field.
func URLPathLT(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldURLPath, v))
}

// URLPathLTE applies the LTE predicate on the "url_path" field.
func URLPathLTE(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldURLPath, v))
}

// URLPathContains applies the Contains predicate on the "url_path" field.
func URLPathContains(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContains(FieldURLPath, v))
}

// URLPathHasPrefix applies the HasPrefix predicate on the "url_path" field.
func URLPathHasPrefix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasPrefix(FieldURLPath, v))
}

// URLPathHasSuffix applies the HasSuffix predicate on the "url_path" field.
func URLPathHasSuffix(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldHasSuffix(FieldURLPath, v))
}

// URLPathEqualFold applies the EqualFold predicate on the "url_path" field.
func URLPathEqualFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEqualFold(FieldURLPath, v))
}

// URLPathContainsFold applies the ContainsFold predicate on the "url_path" field.
func URLPathContainsFold(v string) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldContainsFold(FieldURLPath, v))
}

// ProjectorVersionEQ applies the EQ predicate on the "projector_version" field.
func ProjectorVersionEQ(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldProjectorVersion, v))
}

// ProjectorVersionNEQ applies the NEQ predicate on the "projector_version" field.
func ProjectorVersionNEQ(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldProjectorVersion, v))
}

// ProjectorVersionIn applies the In predicate on the "projector_version" field.
func ProjectorVersionIn(vs ...int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldProjectorVersion, vs...))
}

// ProjectorVersionNotIn applies the NotIn predicate on the "projector_version" field.
func ProjectorVersionNotIn(vs ...int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldProjectorVersion, vs...))
}

// ProjectorVersionGT applies the GT predicate on the "projector_version" field.
func ProjectorVersionGT(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldProjectorVersion, v))
}

// ProjectorVersionGTE applies the GTE predicate on the "projector_version" field.
func ProjectorVersionGTE(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldProjectorVersion, v))
}

// ProjectorVersionLT applies the LT predicate on the "projector_version" field.
func ProjectorVersionLT(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldProjectorVersion, v))
}

// ProjectorVersionLTE applies the LTE predicate on the "projector_version" field.
func ProjectorVersionLTE(v int) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldProjectorVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SearchDocument {
	return predicate.SearchDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SearchDocument) predicate.SearchDocument {
	return predicate.SearchDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SearchDocument) predicate.SearchDocument {
	return predicate.SearchDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SearchDocument) predicate.SearchDocument {
	return predicate.SearchDocument(sql.NotPredicates(p))
}
