// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"balanciz/ent/predicate"
	"balanciz/ent/searchusagestat"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SearchUsageStatDelete is the builder for deleting a SearchUsageStat entity.
type SearchUsageStatDelete struct {
	config
	hooks    []Hook
	mutation *SearchUsageStatMutation
}

// Where appends a list predicates to the SearchUsageStatDelete builder.
func (susd *SearchUsageStatDelete) Where(ps ...predicate.SearchUsageStat) *SearchUsageStatDelete {
	susd.mutation.Where(ps...)
	return susd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (susd *SearchUsageStatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, susd.sqlExec, susd.mutation, susd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (susd *SearchUsageStatDelete) ExecX(ctx context.Context) int {
	n, err := susd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (susd *SearchUsageStatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(searchusagestat.Table, sqlgraph.NewFieldSpec(searchusagestat.FieldID, field.TypeInt))
	if ps := susd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, susd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	susd.mutation.done = true
	return affected, err
}

// SearchUsageStatDeleteOne is the builder for deleting a single SearchUsageStat entity.
type SearchUsageStatDeleteOne struct {
	susd *SearchUsageStatDelete
}

// Where appends a list predicates to the SearchUsageStatDelete builder.
func (susdo *SearchUsageStatDeleteOne) Where(ps ...predicate.SearchUsageStat) *SearchUsageStatDeleteOne {
	susdo.susd.mutation.Where(ps...)
	return susdo
}

// Exec executes the deletion query.
func (susdo *SearchUsageStatDeleteOne) Exec(ctx context.Context) error {
	n, err := susdo.susd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{searchusagestat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (susdo *SearchUsageStatDeleteOne) ExecX(ctx context.Context) {
	if err := susdo.Exec(ctx); err != nil {
		panic(err)
	}
}
