// Code generated by ent, DO NOT EDIT.

package searchrecentquery

import (
	"balanciz/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldUserID, v))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldCompanyID, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldQuery, v))
}

// QueriedAt applies equality check predicate on the "queried_at" field. It's identical to QueriedAtEQ.
func QueriedAt(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldQueriedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLTE(FieldUserID, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v uint) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLTE(FieldCompanyID, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldContainsFold(FieldQuery, v))
}

// QueriedAtEQ applies the EQ predicate on the "queried_at" field.
func QueriedAtEQ(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldEQ(FieldQueriedAt, v))
}

// QueriedAtNEQ applies the NEQ predicate on the "queried_at" field.
func QueriedAtNEQ(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNEQ(FieldQueriedAt, v))
}

// QueriedAtIn applies the In predicate on the "queried_at" field.
func QueriedAtIn(vs ...time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldIn(FieldQueriedAt, vs...))
}

// QueriedAtNotIn applies the NotIn predicate on the "queried_at" field.
func QueriedAtNotIn(vs ...time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldNotIn(FieldQueriedAt, vs...))
}

// QueriedAtGT applies the GT predicate on the "queried_at" field.
func QueriedAtGT(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGT(FieldQueriedAt, v))
}

// QueriedAtGTE applies the GTE predicate on the "queried_at" field.
func QueriedAtGTE(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldGTE(FieldQueriedAt, v))
}

// QueriedAtLT applies the LT predicate on the "queried_at" field.
func QueriedAtLT(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLT(FieldQueriedAt, v))
}

// QueriedAtLTE applies the LTE predicate on the "queried_at" field.
func QueriedAtLTE(v time.Time) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.FieldLTE(FieldQueriedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SearchRecentQuery) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SearchRecentQuery) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SearchRecentQuery) predicate.SearchRecentQuery {
	return predicate.SearchRecentQuery(sql.NotPredicates(p))
}
